### PR TITLE
Add a mustexist option to emit error if files are missing

### PR DESCRIPTION
**Pull request by hadrienk**
This add an mustexist option to fix the issue #89

### CODE REVIEW

**Comment by jonkemp** [comment]
I'm not interested in adding this. Thanks!

**Comment by basti1302** [comment]
Actually that would be a very useful option. :-(   My team just debugged for a good amount of hours where the app worked when it was build on Windows but was missing some JS when it was build on Linux/MacOS (the reason was a upper-case/lower-case error in a JS reference). A failing build would have spent us a lot of trouble.

**Comment by jonkemp** [comment]
Rethinking this.

**Comment by basti1302** [comment]
FWIW, I'm using a [branch](https://github.com/basti1302/gulp-useref/tree/branch-1.3.0-with-mustexist) of the 1.3.0 tag with this change applied in my project right now. Works great. The patch did not apply cleanly anymore but it's a small change, so reapplying it was not a big deal.

**Comment by basti1302** [comment]
\o/

**Comment by jonkemp** [comment]
The functionality is changed though from the PR. There is not a `mustexist` option. Upgrading `vinyl-fs` changed the behavior where instead of ignoring it, it now throws an error if the file is missing.

So I merged the PR, but got rid of the option, added the ability to emit the error from the stream and kept some of the unit tests. It should make sense if you look at the commit history.

**Pull request merged**
