### PR TITLE
Migration Notes v2->v3

### PR DESCRIPTION
**Pull request by rwillmer**
#153

### CODE REVIEW

**Comment by jonkemp** [comment]
Looks pretty good. I just have two requests. First, please add code formatting to the error examples to make them more readable. Second, if you like, I would be willing to move this section up above the Options section. It's pretty relevant and someone scanning the docs could find it faster higher up. It's also more related to the Usage section.

**Comment by rwillmer** [comment]
How about this? I'd prefer to leave the migration section at the end, because over time, it will become less relevant. But I've added a mention of the errors and that section at the top.

**Comment by jonkemp** [comment]
Please squash the commits and I'll accept this change. Thanks!

**Comment by rwillmer** [comment]
Squashed. I think. (Haven't done this before so let me know if I need to do something else)

**Pull request merged**
