### PR TITLE
Fixes incorrect path resolution when alternative search path has file…

### LINKED ISSUE #146: Incorrect join of search paths with file separator and relative file paths
Hello! Recently I found error in `gulp-useref@3.0.3` which leads to bad path resolution and unfortunately to plugin error.

Imagine we have alternative paths and one of those paths has file separator:

```html
<!-- build:css({.tmp/serve,src}) styles/vendor.css -->
  <link rel="stylesheet" href="../vendor/some/file.css" />
<!-- endbuild -->
```

Line [109](https://github.com/jonkemp/gulp-useref/blob/master/index.js#L109) of `index.js` joins HTML file CWD and search paths. So if `file.cwd` is kind of `/a/b/c` we'll have following search path:

    /a/b/c/{.tmp/serve,src}

Then, we create search pattern for `node-glob` on line [116](https://github.com/jonkemp/gulp-useref/blob/master/index.js#L116). And if we run `path.join()` for search path and `../vendor/some/file.css`, we'll get the following:

   /a/b/c/{.tmp/vendor/some/file.css

And this leads to error.

P.S.: OS X, node 4.2.2, npm 2.14.7

### PR DESCRIPTION
**Pull request by estliberitas**
… separator

Fixes #146

### CODE REVIEW

**Comment by jonkemp** [comment]
I'm good with this. Can you squash your commits?

**Comment by estliberitas** [comment]
Done.

**Comment by estliberitas** [comment]
@jonkemp Will you release 3.0.1 soon?

**Comment by jonkemp** [comment]
Published.

**Pull request merged**
