### PR TITLE
Supporting absolute paths

### LINKED ISSUE #123: Can't pass absolute path as searchPath
I was running into an empty stream when passing an absolute path as my `searchPath`. I kind of expected gulp-useref not to fail silently on an empty glob result, but anyway, the reason why it doesn't work is [this call to `path.join()`](https://github.com/jonkemp/gulp-useref/blob/7f7d8d85e8f7c0935c598969ebd02a6cda055ce8/index.js#L15) (and presumably the one a few lines higher too).

Would changing that call to a `path.resolve()` break anything? In my case, it worked fine.

As a workaround, I used `path.relative(__dirname, dir)` to get a relative path, but supporting absolute paths seems like a useful feature.

### PR DESCRIPTION
**Pull request by timdp**
Fixes #123.

### CODE REVIEW

**Comment by jonkemp** [comment]
Can you add a test case where it is breaking before adding this fix?

**Comment by timdp** [comment]
Absolutely. Would you like me to squash them into one commit?

**Comment by jonkemp** [comment]
Yes, please.

**Comment by timdp** [comment]
No sweat.

**Pull request merged**
